In [49]:
import h5py
import matplotlib.pyplot as plt
import numpy as np
initial_mass = 0.9937363275412056
remnant_mass     =  0.951609417715
#a= -1.58925e-13,1.181e-13,2.56273174999e-10
initial_spin1     =  np.array([0.082242988313 ,0.0394766344682 ,-0.0526355124943])
initial_spin2     = np.array([ 0.0181850419292 ,0.00909252094152 ,-0.0181850419402])
remnant_spin     =  np.array([-6.60625106334e-10, 6.70538896538e-10, 0.621632567933])
initial_j =  np.array([0.0000000427581822,  -0.0000002342625073,   1.1847155663506601])
alm = []
H2 = []

input_file1 = h5py.File('rhOverM_Asymptotic_GeometricUnits.h5','r')
SXS = input_file1['Extrapolated_N2.dir']['Y_l%i_m%i.dat'%(2,-1)]
t = SXS[:,0]
dt = np.diff(t)
def f(l,m):
    return np.sqrt((l-m)*(l+m+1))
def ALM(l,m):
    if m>l or m<-l:
        return 0
    return alm[l-2][m+l]
def Hcomp(l,m):
    
    return H2[l-2][m+l]



In [50]:

for l in range(2,9):
    alm.append([])
    H2.append([])
    for m in range(-l,l+1):
        SXS = input_file1['Extrapolated_N2.dir']['Y_l%i_m%i.dat'%(l,m)]
        H = SXS[:,1]+(0+1j)*SXS[:,2]
        t = SXS[:,0]
        Hdot = np.diff(H)/np.diff(t)
        alm[l-2].append(Hdot)
        H2[l-2].append(H[1:])

            




In [51]:

djx = dt*0
djy = djx
djz = djx
de = djx
for l in range(2,9):
    for m in range(-l,l+1):
        djx = djx + np.imag(Hcomp(l,m)*(f(l,m)*np.conj(ALM(l,m+1)) + f(l,-m)*np.conj(ALM(l,m-1))))
        djy = djy - np.real(Hcomp(l,m)*(f(l,m)*np.conj(ALM(l,m+1)) - f(l,-m)*np.conj(ALM(l,m-1))))
        djz = djz + np.imag(m*Hcomp(l,m)*np.conj(ALM(l,m)))
        de = de + ALM(l,m)*np.conj(ALM(l,m))   

In [52]:
JX = np.cumsum(djx*dt)/(32*np.pi)
JY = np.cumsum(djy*dt)/(32*np.pi)
JZ = np.cumsum(djz*dt)/(16*np.pi)
E = np.cumsum(de*dt)/(16*np.pi)
final_mass = initial_mass - E[-1]
print(remnant_mass,final_mass,(remnant_mass-final_mass)/remnant_mass)

radiation_spin = np.array([JX[-1],JY[-1],JZ[-1]])
final_spin = initial_j - radiation_spin
print(remnant_spin,final_spin)
print((remnant_spin-final_spin)/remnant_spin)
Jsq_init= (remnant_spin[0]*remnant_spin[0]+remnant_spin[1]*remnant_spin[1])
Jsq_final = final_spin[0]*final_spin[0]+final_spin[1]*final_spin[1]
print((Jsq_init-Jsq_final)/(Jsq_init))

(0.951609417715, (0.95165445693454542+0j), (-4.7329522708602253e-05+0j))
(array([ -6.60625106e-10,   6.70538897e-10,   6.21632568e-01]), array([  4.26854073e-08,  -2.34565103e-07,   6.22618634e-01]))
[  6.56136620e+01   3.50815804e+02  -1.58625220e-03]
-64152.2234153


In [48]:


print(Final_spin2,radiation_spin)

(array([  4.34188073e-08,  -2.34933046e-07,   5.63082998e-01]), array([  7.27748553e-11,   3.02595895e-10,   5.62096932e-01]))
