In [1]:
%matplotlib inline
import numpy as np
import remnant_quantities as rq
import simulation_data as sd
import matplotlib.pyplot as plt
import bisect
import errors
path = '../../Data/023'
directory = 'Extrapolated_N2.dir'
err = errors.Error(path,directory)
sim = err.getHighResSim()



In [2]:
print(sim.metadata.remnant_spin)
print(err.highResSpin(),err.downSampleErrorSpin(),err.extrapolationErrorSpin(),err.junkErrorSpin(),
      err.limitedModesErrorSpin(),err.truncErrorSpin())
print(sim.metadata.remnant_mass)
print(err.highResMass(),err.downSampleErrorMass(),err.extrapolationErrorMass(),err.junkErrorMass(),
      err.limitedModesErrorMass(),err.truncErrorMass())
print(err.highResMass(),1)
print(err.limitedModesErrorSpin())

[ 0.09077469 -0.04171651  0.61395447]
(0.62302124568097073, 0.0001805928150584446, 0.0091846401903944441, 0.0026675845014919597, 3.6446662959876974e-06, 0.0016520704413518494)
0.953512795609
(array(0.9537450599958115), 1.5741926689294417e-05, 0.00037663837663715061, 0.0001158984393888618, 1.5809636306762798e-06, 0.00038994992617014113)
(array(0.9537450599958115), 1)
3.64466629599e-06


In [37]:
print(len(ALM),len(sim1.time))
sim1.time
# [ 0.0907202  -0.0423091   0.61492703]
# [ 0.09010636 -0.04240313  0.61154324]
# [ 0.08842172 -0.04406088  0.59927644]
# [ 0.08918557 -0.04146931  0.60590561]
# 0.953745059996
# 0.952904474808
# 0.945617280141
# 0.953368421619
# 977.08586495
# 1029.11268763
# 1398.00487901
# 971.256516661

(20476, 20478)


array([  160.20782182,   160.70772267,   161.20762352, ...,  6609.17749156,
        6609.27746974,  6609.37744792])

In [17]:
a = [5,6,7,8]
print(bisect.bisect_right(a,6))
i = bisect.bisect_right(a,6)
print(a[i-1:])

2
[6, 7, 8]
