In [1]:

import numpy as np
import remnant_quantities as rq
import simulation_data as sd
import matplotlib.pyplot as plt
path = '../../Data/023/Lev4/'
sim1 = sd.Simulation(path,'Extrapolated_N2.dir')
sim2 = sd.Simulation(path,'Extrapolated_N3.dir')
sim3 = sd.Simulation(path,'Extrapolated_N4.dir')
sim4 = sd.Simulation(path,'OutermostExtraction.dir')

In [5]:
print(sim1.metadata.remnant_mass)
print(sim1.metadata.remnant_spin)
mass1 = rq.getRemnantMass(sim1)
mass2 = rq.getRemnantMass(sim2)
mass3 = rq.getRemnantMass(sim3)
mass4 = rq.getRemnantMass(sim4)
spin1 = rq.getRemnantSpin(sim1)
spin2 = rq.getRemnantSpin(sim2)
spin3 = rq.getRemnantSpin(sim3)
spin4 = rq.getRemnantSpin(sim4)
kick1 = rq.getKick(sim1)
kick2 = rq.getKick(sim2)
kick3 = rq.getKick(sim3)
kick4 = rq.getKick(sim4)
print(spin1)
print(spin2)
print(spin3)
print(spin4)

print(mass1)
print(mass2)
print(mass3)
print(mass4)

print(kick1)
print(kick2)
print(kick3)
print(kick4)
plt.figure()
ALM = np.diff(sim2.alm[0][0])/sim2.dt[1:]
plt.plot(sim2.time[2:],ALM)
plt.show()

0.953295317619
[ 0.09075904 -0.04172185  0.61370673]
[ 0.09040949 -0.04229813  0.6132998 ]
[ 0.08874562 -0.04230203  0.60448546]
[ 0.08368985 -0.04329062  0.57733142]
[ 0.08926452 -0.04155099  0.60641181]
0.95335511007
0.951150640699
0.943135639264
0.953295377096
1017.90057864
1174.95209762
1767.36561699
993.403039929


In [3]:
print(len(ALM),len(sim1.time))
sim1.time
# [ 0.0907202  -0.0423091   0.61492703]
# [ 0.09010636 -0.04240313  0.61154324]
# [ 0.08842172 -0.04406088  0.59927644]
# [ 0.08918557 -0.04146931  0.60590561]
# 0.953745059996
# 0.952904474808
# 0.945617280141
# 0.953368421619
# 977.08586495
# 1029.11268763
# 1398.00487901
# 971.256516661

(20923, 20925)


array([ -108.74122509,  -108.24132697,  -107.74142884, ...,  6571.961435  ,
        6572.06141204,  6572.16138909])