In [184]:
%matplotlib inline
initial_mass = 0.9932835557603398
remnant_mass     =  0.956545323918
#a= -1.58925e-13,1.181e-13,2.56273174999e-10
initial_spin1     =  np.array([0.082242988313 ,0.0394766344682 ,-0.0526355124943])
initial_spin2     = np.array([ 0.0181850419292 ,0.00909252094152 ,-0.0181850419402])
remnant_spin     =  np.array([0.0466094549397, 0.0275813208324, 0.579078414003])
initial_j =  np.array([0.1005730323308390,   0.0447975576151179,   1.0425979162747623])
alm = []
H2 = []
import h5py
import matplotlib.pyplot as plt
import numpy as np
input_file1 = h5py.File('rhOverM_Asymptotic_GeometricUnits006.h5','r')
SXS = input_file1['Extrapolated_N2.dir']['Y_l%i_m%i.dat'%(2,-1)]
t = SXS[:,0]
dt = np.diff(t)
def f(l,m):
    return np.sqrt((l-m)*(l+m+1))
def ALM(l,m):
    if m>l or m<-l:
        return 0
    return alm[l-2][m+l]
def Hcomp(l,m):
    
    return H2[l-2][m+l]



In [185]:

for l in range(2,9):
    alm.append([])
    H2.append([])
    for m in range(-l,l+1):
        SXS = input_file1['Extrapolated_N2.dir']['Y_l%i_m%i.dat'%(l,m)]
        H = SXS[:,1]+(0+1j)*SXS[:,2]
        t = SXS[:,0]
        Hdot = np.diff(H)/np.diff(t)
        alm[l-2].append(Hdot)
        H2[l-2].append(H[1:])

            




In [186]:

djx = dt*0
djy = djx
djz = djx
de = djx
for l in range(2,9):
    for m in range(-l,l+1):
        djx = djx + np.imag(Hcomp(l,m)*(f(l,m)*np.conj(ALM(l,m+1)) + f(l,-m)*np.conj(ALM(l,m-1))))
        djy = djy - np.real(Hcomp(l,m)*(f(l,m)*np.conj(ALM(l,m+1)) - f(l,-m)*np.conj(ALM(l,m-1))))
        djz = djz + np.imag(m*Hcomp(l,m)*np.conj(ALM(l,m)))
        de = de + ALM(l,m)*np.conj(ALM(l,m))   

In [187]:
JX = np.cumsum(djx*dt)/(32*np.pi)
JY = np.cumsum(djy*dt)/(32*np.pi)
JZ = np.cumsum(djz*dt)/(16*np.pi)
E = np.cumsum(de*dt)/(16*np.pi)
final_mass = initial_mass - E[-1]
print(remnant_mass,final_mass,(remnant_mass-final_mass)/remnant_mass)

radiation_spin = np.array([JX[-1],JY[-1],JZ[-1]])
final_spin = initial_j - radiation_spin
print(remnant_spin,final_spin)
print((remnant_spin-final_spin)/remnant_spin)
Jsq_init= np.sqrt((remnant_spin[0]*remnant_spin[0]+remnant_spin[1]*remnant_spin[1]))
Jsq_final = np.sqrt(final_spin[0]*final_spin[0]+final_spin[1]*final_spin[1])
print((Jsq_init-Jsq_final)/(Jsq_init))


(0.956545323918, (0.95648006344574177+0j), (6.8225175144740865e-05+0j))
(array([ 0.04660945,  0.02758132,  0.57907841]), array([ 0.04661495,  0.0275272 ,  0.57943781]))
[-0.00011786  0.00196226 -0.00062063]
0.000421213485612


In [188]:

Final_spin2 = initial_j - remnant_spin

print(Final_spin2,radiation_spin)

(array([ 0.05396358,  0.01721624,  0.4635195 ]), array([ 0.05395808,  0.01727036,  0.46316011]))


SyntaxError: invalid syntax (<ipython-input-143-5305b7e52cfe>, line 1)